### ISSUE TITLE
MissingMethodException when setting VatNumber property on ICustomer

### ISSUE THREAD

**Issue by TimS-** [kfrancis/chargify-dot-net#27]
I updated to the latest build on Nuget to implement VatNumber functionality since a PR https://github.com/kfrancis/chargify-dot-net/pull/15, however I am getting the following error when I try to call my method which gets a customer and updates the VatNumber property - assuming it's not been fully implemented?

```
System.MissingMethodException was unhandled by user code
Method not found: 'Void ChargifyNET.ICustomerAttributes.set_VatNumber(System.String)'.
```

**Comment by kfrancis** [comment]
That's because you aren't supposed to set output object properties, `CustomerAttributes` has `VatNumber` which is what you set (or alternatively `SubscriptionCreateOptions`).

It's not a great structure, I agree - I just haven't had time to work on the better structured lib (input/output poco serialization, better overall structure, using RestSharp and not .NET vanilla, .NET Core 1 compat, etc). This library is in use by thousands, so I can't make too many breaking changes.
