### ISSUE TITLE
The type or namespace name 'IMetafield' could not be found

### ISSUE THREAD

**Issue by MartyIce** [kfrancis/chargify-dot-net#64]
Where is IMetafield (referenced by ChargifyConnect class) defined?  I did a clean pull and am seeing the following error trying to build (in VS2017):

The type or namespace name 'IMetafield' could not be found (are you missing a using directive or an assembly reference?)	ChargifyDotNet(netstandard2.0)	

\chargify-dot-net\Source\ChargifyDotNet\ChargifyConnect.cs	215

**Comment by OSPete** [comment]
When I pulled it down the other day I ran into this and after looking around it looks like it was pulled in during the issue fix for #61 - I couldn't find any references to it in the code in my quick search and a google search seems to lead to some sitefinity CMS thing? I dunno. 

Since I couldn't find any reference to the code within the library itself, I just removed that method and everything built fine.

**Comment by robfarmergt** [comment]
That worked for me as well, thanks!

**Comment by OSPete** [comment]
No problem!

Some more searching and there does seem to be some metafields/metadata functionality related to subscriptions supported by the API: https://www.chargify.com/blog/metafields-and-metadata-api-endpoints/
So this might be the in progress (ie: incomplete) work on implementing that, i haven't looked at the code close enough to confirm this though.

**Comment by kfrancis** [comment]
Sorry everyone, this was related to some code that hadn't been checked in.
